name: Website Build and Test

on: 
  pull_request:
    branches: 
      - master
    paths: 
      - website/**

jobs:
  build:
    name: "Website Build and Test"

    runs-on: ubuntu-latest

    steps:
    - name: Update PR Label
      uses: actions/github-script@0.4.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['Website']
          })
          
    - name: Checkout Branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
      
    - name: Setup Node 
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Yarn Install
      run: cd $GITHUB_WORKSPACE/website && yarn install
  
    - name: Yarn Build
      run: cd $GITHUB_WORKSPACE/website && yarn build

    - name: Yarn Audit
      run: cd $GITHUB_WORKSPACE/website && yarn lint --audit-level=moderate
      env:
        CI: true
        
    - name: Commit files
      run: |
        cd $GITHUB_WORKSPACE
        git add docs/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add docs folder with the build files" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{github.head_ref}}
