name: WPF Unit Tests

on: 
  pull_request:
    branches: 
      - master
    paths:
      - WPF/**


jobs:
  WPF:
    name: Unit Tests
    runs-on: [windows-latest]

    steps:
      - name: Update PR Label
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['WPF']
            })

      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1
      - name: get Nuget packages
        run: |
          cd $Env:GITHUB_WORKSPACE\WPF\SeeShells
          nuget restore
      - name: Build WPF
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\WPF\SeeShells\SeeShells.sln
      - name: Run Tests
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\"
          .\vstest.console.exe $Env:GITHUB_WORKSPACE\WPF\SeeShells\SeeShellsTests\bin\Debug\SeeShellsTests.dll /Parallel /TestCaseFilter:"TestCategory!=OnlineTest"
