name: WPF Unit Tests

on: 
  pull_request:
    branches: 
      - master

jobs:
  WPF:
    name: Unit Tests
    runs-on: [windows-latest]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1
      - name: get Nuget packages
        run: |
          cd $Env:GITHUB_WORKSPACE\WPF\SeeShells
          nuget restore
      - name: Build WPF
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\WPF\SeeShells\SeeShells.sln
      - name: Run Tests
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\"
          .\vstest.console.exe $Env:GITHUB_WORKSPACE\WPF\SeeShells\SeeShellsTests\bin\Debug\SeeShellsTests.dll /Parallel /TestCaseFilter:"TestCategory!=OnlineTest"
